//======================Question 23=======================
var car = 'GTR';
console.log("Is car == 'GTR'?");
console.log(car == 'GTR');
console.log();
var subject = "computer";
console.log("Is subject == 'computer'");
console.log(subject == "chemistry");
console.log();
var day = "Monday";
console.log("Is day == 'Monday");
console.log(day == "Monday");
console.log();
var language = "typescript";
console.log("Is language == 'typescript'");
console.log(language == "javascript");
console.log();
var names = "Abdul Samad";
console.log("Is name == 'Abdul Samad'");
console.log(names == "Abdul Samad");
console.log();
var mobile = "Techno";
console.log("Is mobile == 'Techno'");
console.log(mobile == "Iphone");
console.log();
var cpu = "Core i7";
console.log("Is CPU == 'Core i7'");
console.log(cpu == "Core i7");
console.log();
var bike = "Kawasaki";
console.log("Is BIKE == 'Kawasaki'");
console.log(bike == "Cd 70");
console.log();
var weather = "cloudy";
console.log("Is weather == 'cloudy'");
console.log(weather == "cloudy");
console.log();
var age = "16";
console.log("Is age == '16'");
console.log(age == "17");
